export const capabilities = [
  "Figma URL parsing",
  "File and node ID extraction",
  "Local credentials",
  "Rate-limit aware fetching",
  "Request deduplication",
  "Local cache",
  "Versioned snapshots",
  "Offline snapshot review",
  "Design simplification",
  "Token extraction",
  "Asset export",
  "Canonical asset manifests",
  "Evidence and confidence scoring",
  "Clarification requests",
  "Visual compare",
  "Component mappings",
  "Debug bundles",
  "Local logs",
  "MCP tool output",
  "CLI JSON output",
];
